//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Linq;
namespace Capital_Life_Insurance_LLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidateCard()
        {
            this.Grade = new HashSet<Grade>();
            this.CandidateEducation = new HashSet<CandidateEducation>();
        }

        public string FIO
        {
            get
            {
                return FirstName + " " + Name + " " + Patranomic;
            }
        }
        public string PositionToString
        {
            get
            {
                return Positions.PositionsTitle.ToString();
            }
        }
        public string Date
        {
            get
            {
                return Bithday.ToString();
            }
        }
        public string EducationName
        {
            get
            {
                return GetEducation();
            }
        }

        public string EduТName
        {
            get
            {
                
                string s = string.Join(", ", CandidateEducation.Select(ce => ce.Education1.EducationLevel));
                if (s=="")
                {
                    return "Нет";
                }
                else
                    return string.Join(", ", CandidateEducation.Select(ce => ce.Education1.EducationLevel));
            }
        }
        
        public int CandidateID { get; set; }
        public string FirstName { get; set; }
        public string Name { get; set; }
        public string Patranomic { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime Bithday { get; set; }
        public int Position { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual Positions Positions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grade { get; set; }
    }
}
