//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capital_Life_Insurance_LLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateEducation
    {
        public int CandidateEducationID { get; set; }
        public Nullable<int> Candidate { get; set; }
        public Nullable<int> Education { get; set; }
    
        public virtual CandidateCard CandidateCard { get; set; }
        public virtual Education Education1 { get; set; }
        public string EducationNameString
        {
            get
            {
                return Education1.EducationLevel.ToString();
            }
        }
    }
}
