//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capital_Life_Insurance_LLC
{
    using System;
    using System.Linq;
    using System.Collections.Generic;

    using System.Windows;

    public partial class CandidateCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidateCard()
        {
            this.Grade = new HashSet<Grade>();
            this.CandidateEducation = new HashSet<CandidateEducation>();
        }

        public string FIO
        {
            get
            {
                return FirstName + " " + Name + " " + Patranomic;
            }
        }
        public string PositionToString
        {
            get
            {
                return Positions.PositionsTitle.ToString();
            }
        }
        public string Date
        {
            get
            {
                return Bithday.ToString();
            }
        }
        public string EduТName
        {
            get
            {

                string s = string.Join(", ", CandidateEducation.Select(ce => ce.Education1.EducationLevel));
                if (s == "")
                {
                    return "Нет";
                }
                else
                    return string.Join(", ", CandidateEducation.Select(ce => ce.Education1.EducationLevel));
            }
        }
        public string GradeALL
        {
            get
            {
                if (this.Grade == null || !this.Grade.Any())
                {
                    return "Нет";
                }

                var grades = this.Grade.Where(g => g.Grade1.HasValue).Select(g => g.Grade1.Value);

                if (!grades.Any())
                {
                    return "Нет";
                }
                else
                {
                    return grades.Average().ToString("F1");
                }
            }
        }

        public Visibility Vis
        {
            get
            {

                if (RoleId.ID == 3)
                    return Visibility.Visible;
                else
                    return Visibility.Collapsed;

            }
        }
        public int CandidateID { get; set; }
        public string FirstName { get; set; }
        public string Name { get; set; }
        public string Patranomic { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime Bithday { get; set; }
        public int Position { get; set; }
        public string PhotoPath { get; set; }
        public int CreateUserID { get; set; }
    
        public virtual Positions Positions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grade { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateEducation> CandidateEducation { get; set; }
    }
}
